---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "plan-to-podcast-config"
data:
  config.toml: |
    [server]
    port = 8501
    fileWatcherType = "none"
    headless = true
    sslCertFile = "/etc/secret-volume/tls.crt"
    sslKeyFile = "/etc/secret-volume/tls.key"

    [browser]
    gatherUsageStats = false

    [theme]
    base = "dark"
